In [2]:
import torch 
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim 

torch.manual_seed(1)

In [27]:
#1D vector 
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [7]:
#2D metrix
M_data = [[1., 2., 3.], [4., 5., 6.]]
M = torch.tensor(M_data)
print(M)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
#3D 
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [9]:
print(V[0])

tensor(1.)


In [17]:
print(V[0].item())

1.0


In [16]:
print(M[0]) #start from 0

tensor([1., 2., 3.])


In [21]:
#print(M[0].item()) #ValueError: only one element tensors can be converted to Python scalars
print(M[0,0].item())

1.0


In [24]:
print(T[0])

tensor([[1., 2.],
        [3., 4.]])


In [28]:
#float vs. long --> two different datatype 
V_data = [1., 2., 3.]
V = torch.LongTensor(V_data)
print(V)

tensor([1, 2, 3])


In [29]:
x = torch.randn((3,4,5)) #3*4*5 3D tensor 
print(x)

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])


In [37]:
x = torch.tensor([1.,2.,3.])
y = torch.tensor([4.,5.,6.])
z = x + y
print(z)

tensor([5., 7., 9.])


In [41]:
x_1 = torch.randn(2,5) #2 * 5 * 1
y_1 = torch.randn(3,5) # 3 * 5 * 1
print(x_1)
print(y_1)

tensor([[ 1.6015, -1.0735, -1.2173,  0.6472, -0.0412],
        [-0.1775, -0.5000,  0.8673, -0.2732, -0.4608]])
tensor([[-0.0991,  0.4728,  1.0049, -0.2871, -1.1619],
        [ 0.0276,  0.5652, -0.0115,  0.6706, -0.4929],
        [ 1.5050, -2.3264,  1.6169, -0.9026,  0.1737]])


In [43]:
#concatenates along the first axis 
z_1 = torch.cat([x_1, y_1])
print(z_1) #5 *5 *1

tensor([[ 1.6015, -1.0735, -1.2173,  0.6472, -0.0412],
        [-0.1775, -0.5000,  0.8673, -0.2732, -0.4608],
        [-0.0991,  0.4728,  1.0049, -0.2871, -1.1619],
        [ 0.0276,  0.5652, -0.0115,  0.6706, -0.4929],
        [ 1.5050, -2.3264,  1.6169, -0.9026,  0.1737]])


In [45]:
x_2 = torch.randn(2,3)
y_2 = torch.randn(2,5)
print(x_2)
print(y_2)

tensor([[ 1.4697, -0.3951, -0.5101],
        [ 1.1163, -0.5926,  0.9089]])
tensor([[-1.0792, -0.6751,  1.4083, -1.8456, -0.5655],
        [-0.9094, -0.4891, -0.6175,  0.3836,  0.3852]])


In [47]:
z_2 = torch.cat([x_2,y_2],1)
print(z_2)

tensor([[ 1.4697, -0.3951, -0.5101, -1.0792, -0.6751,  1.4083, -1.8456, -0.5655],
        [ 1.1163, -0.5926,  0.9089, -0.9094, -0.4891, -0.6175,  0.3836,  0.3852]])


In [4]:
x = torch.randn(2,3,4)
print(x)
print(x.view(2,12))
print(x.view(2, -1))

tensor([[[-1.8821, -0.7765,  2.0242, -0.0865],
         [ 0.0981, -1.2150,  0.7312,  1.1718],
         [-0.0255, -1.0233, -0.5962, -1.0055]],

        [[-0.2106, -0.0075,  1.6734,  0.0103],
         [-0.7040, -0.1853, -0.9962, -0.8313],
         [-0.4610, -0.5601,  0.3956, -0.9823]]])
tensor([[-1.8821, -0.7765,  2.0242, -0.0865,  0.0981, -1.2150,  0.7312,  1.1718,
         -0.0255, -1.0233, -0.5962, -1.0055],
        [-0.2106, -0.0075,  1.6734,  0.0103, -0.7040, -0.1853, -0.9962, -0.8313,
         -0.4610, -0.5601,  0.3956, -0.9823]])
tensor([[-1.8821, -0.7765,  2.0242, -0.0865,  0.0981, -1.2150,  0.7312,  1.1718,
         -0.0255, -1.0233, -0.5962, -1.0055],
        [-0.2106, -0.0075,  1.6734,  0.0103, -0.7040, -0.1853, -0.9962, -0.8313,
         -0.4610, -0.5601,  0.3956, -0.9823]])


In [13]:
x = torch.tensor([1.,2.,3],requires_grad = True)
y = torch.tensor([4.,5.,6],requires_grad = True)
z = x + y
print(z)
print(z.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [14]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [16]:
s.backward()
print(x.grad)

tensor([2., 2., 2.])


In [17]:
x = torch.randn(2,2)
y = torch.randn(2,2)
print(x.requires_grad,y.requires_grad)
z = x + y
print(z.grad_fn)

False False
None


In [18]:
x = x.requires_grad_()
y = y.requires_grad_()
z = x + y
print(z.grad_fn)
print(z.requires_grad)

True


In [25]:
new_z = z.detach()
print(z)
print(new_z)
print(new_z.grad_fn)

tensor([[-0.3985,  1.1431],
        [-0.3419,  0.0478]], grad_fn=<AddBackward0>)
tensor([[-0.3985,  1.1431],
        [-0.3419,  0.0478]])
None


In [22]:
print(x.requires_grad)
print((x ** 2).requires_grad)

print((x ** 2).grad_fn)

True
True


In [23]:
with torch.no_grad():
    print((x ** 2).requires_grad)

False
